image:
  name: registry.gitlab.com/risserlabs/community/images/kube-commands-terraform-aws:0.0.1

variables:
  TF_ROOT: main

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

stages:
  - plan
  - deploy
  - cleanup

plan:
  stage: plan
  script:
    - make -s plan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan.cache
    reports:
      terraform: ${TF_ROOT}/tfplan.json

deploy:
  stage: deploy
  script:
    - make -s +apply
  needs:
    - plan
  when: manual
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - artifacts

# destroy:
#  stage: cleanup
#  script:
#    - make -s +destroy
#  needs:
#    - plan
#  when: manual
