image:
  name: registry.gitlab.com/risserlabs/community/images/terraform:0.0.1

variables:
  TF_STATE_NAME: main
  TF_ROOT: main

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

stages:
  - plan
  - deploy
  - cleanup

plan:
  stage: plan
  script:
    - make -s plan
  artifacts:
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

deploy:
  stage: deploy
  script:
    - make -s +apply
  needs:
    - plan
  when: manual
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

destroy:
  stage: cleanup
  script:
    - make -s +destroy
  needs:
    - plan
  when: manual
